### ISSUE TITLE
Feedback - Week 16 Project

### ISSUE THREAD

**Issue by ntuvera** [longp/RU-FLYER#16]
Hey @longp, @Alexg2195, @MariaV27, @JulioDVega.  I cloned the repo and started to look around at your code, while comparing the deployed version to my local version...

What you have is a full C.R.U.D. as in Create, Read, Update, Delete ;)  Having spoken to you Long, I know you guys had a last minute rewrite, so I kept that in mind while looking over your files.

You'll need to refactor this application, ie work on routing/modules.exports to clean up your server.js  It'll be good practice for exporting and compartmentalizing.  Keep in mind that you'll be need some folders like `views`, `config`, `models`, `routes`.  When you do this make sure that you `require(xyz')`, where needed in the new files.

Also in terms of your config (ie connecting to servers/dbs), your Sequelize connection is only setup for your JAWSDB_URL (heroku database), you can easily add a || with local parameters for immediate testing on your local database.  I hope you weren't just coding and then pushing to Heroku to test database dependent files.  That's just a waste of time, when you can have a local DB setup with everything you need.  Also I woudl advise creating some kind of seed/schema.sql file so you guys don't have to individually change data and have some kind of similar starting data.  If you changed this after the last push for deployment that is fine, but I noticed you still kept your `PORT = process.env.PORT || 3000`, so I'm not sure why it doesn't parallel your sequelize connection.

Also in terms of hosting your background image is spitting back console.log issues on your hosted site.  This comes down to linking the file via `HTTPS` instead of `HTTP`.  It's a simple fix, but also why are you linking something separate out instead of incorporating this into your `public/assets` folder?

In addition to your file structure and assets, I see a lot of "testonly" or "nodemailer" files/folders.  I don't know why these are included in the master branch.  These files should be in a branch elsewhere and not commited to the master branch.  This will extend out to the workflow of having a master/develop(mergeAll) zone where code should be tested.  Only production code should be in master.  Don't make it  a habit of crossing branches and pushing directly to master without proper testing.  Other devs will not be happy with you.

Also I appreciate that you guys included a .gitignore, people often forget.   But I did notice that there was another .gitignore in your `views` folder,  please spot check your additions in commits on merges / pull requests.

For your validations on the front-end and back-end, I see you've included some here and there.  As a user, these validations are not very clear.  You've defined some rules in yoru models, but do not provide error messges for all conditions, besides a very generic catch all for SOME instances.  There are other instances such as creating events that don't give me any error messages.  I'm sure you've got the templates for these messages, now use them.

You've included the required `express-sessions` basics, but I would really like to have the ability to log out.  While you've used cookies and sessiont o create a user logged in and grab their data, it's still worth creating a log out to complete this feature.  As a tester, I can't create new users and events for testing which is troublesome.  But the completelness of sessions is based on the idea that a session can start and end.

These are the main points I wanted to cover, but I would like to talk to each of you individually and just discuss what you think or if I come up with anything else.

You've pulled out a good functioning C.R.U.D. app that needs polishing.  Great job.  I hope you took the time to take a retrospective and really talk about what you've learned, accomplished, and could improve on.

**Comment by Alexg2195** [comment]
Cleaning up old github issues
